import { assignCourseRoutes } from '../features/assignCourse/assignCourse.route.js';
import { authRoutes } from '../features/auth/auth.routes.js';
import { certificateRoutes } from '../features/certificate/certificate.route.js';
import { courseRoutes } from '../features/course/course.route.js';
import { scormRoutes } from '../features/course/scorm.route.js';
import { companyCoursePurchaseRoutes } from '../features/coursePurchase/companyCoursePurchase.route.js';
import { employeeRoutes } from '../features/employee/employee.route.js';
import { enrollmentRoutes } from '../features/enrollment/enrollment.route.js';
import { lessonRoutes } from '../features/lesson/lesson.route.js';
import { lessonStandaloneRoutes } from '../features/lesson/lesson.standalone.route.js';
import { licenseRoutes } from '../features/license/license.route.js';
import { IncomeRoutes } from '../features/Income/Income.route.js';
import { licensePlanRoutes } from '../features/licensePlan/licensePlan.route.js';
import { notificationRoutes } from '../features/notification/notification.route.js'
import { paymentRoutes } from '../features/payment/payment.routes.js';
import { quizRoutes } from '../features/quiz/quiz.route.js';
import { reviewRoutes } from '../features/reviews/reviews.route.js';
import { supportTicketRoutes } from '../features/supportTicket/supportTicket.route.js';
import { userRoutes } from '../features/user/user.routes.js';
import { healthRoutes } from './health.route.js';
import { staffRoutes } from '../features/staff/staff.route.js';
import { serviceRequestRoutes } from '../features/serviceRequest/serviceRequest.route.js';
import { contactRoutes } from '../features/contact/contact.route.js';
import { collaborationRoutes } from '../features/collaboration/collaboration.route.js';
import { courseReviewRoutes } from '../features/courseReview/courseReview.route.js';
import { coursePackageRoutes } from '../features/coursePackage/coursePackage.route.js';
import { courseFavoriteRoutes } from '../features/courseFavorite/courseFavorite.route.js';
import { packageRoutes } from '../features/package/package.route.js';
import { platformSettingRoutes } from '../features/platformSetting/platformSetting.route.js';
import { companyDashboardRoutes } from '../features/dashboard/companyDashboard.route.js';

const BASE_PATH = '/api/v1';

export default (app) => {

  app.use(healthRoutes);
  app.use(`${BASE_PATH}/auth`, authRoutes);
  app.use(`${BASE_PATH}/users`, userRoutes);
  app.use(`${BASE_PATH}/courses`, courseRoutes);
  app.use(`${BASE_PATH}/licenses`, licenseRoutes);
  app.use(`${BASE_PATH}/payments`, paymentRoutes);
  app.use(`${BASE_PATH}/enrollments`, enrollmentRoutes);
  app.use(`${BASE_PATH}/quizzes`, quizRoutes);
  app.use(`${BASE_PATH}/scorm`, scormRoutes);
  app.use(`${BASE_PATH}/lessons`, lessonStandaloneRoutes);
  app.use(`${BASE_PATH}/license-plans`, licensePlanRoutes);
  app.use(`${BASE_PATH}/assignments`, assignCourseRoutes);
  app.use(`${BASE_PATH}/tickets`, supportTicketRoutes);
  app.use(`${BASE_PATH}/certificates`, certificateRoutes);
  app.use(`${BASE_PATH}/notifications`, notificationRoutes);
  app.use(`${BASE_PATH}/employees`, employeeRoutes);
  app.use(`${BASE_PATH}/reviews`, reviewRoutes);
  app.use(`${BASE_PATH}/course-reviews`, courseReviewRoutes);
  app.use(`${BASE_PATH}/company-purchases`, companyCoursePurchaseRoutes);
  app.use(`${BASE_PATH}/incomes`, IncomeRoutes);
  app.use(`${BASE_PATH}/staff`, staffRoutes);
  app.use(`${BASE_PATH}/service-requests`, serviceRequestRoutes);
  app.use(`${BASE_PATH}/contacts`, contactRoutes);
  app.use(`${BASE_PATH}/collaborations`, collaborationRoutes);
  app.use(`${BASE_PATH}/course-packages`, coursePackageRoutes);
  app.use(`${BASE_PATH}/favorite-courses`, courseFavoriteRoutes);
  app.use(`${BASE_PATH}/packages`, packageRoutes);
  app.use(`${BASE_PATH}/platform-settings`, platformSettingRoutes);
  app.use(`${BASE_PATH}/dashboard`, companyDashboardRoutes);
};
